### ISSUE TITLE
[ FRONT END ] Imagens Post

### ISSUE THREAD

**Issue by comandoDev** [comandoDev/ccon-frontend#4]
- [x] Funcionalidade de adicionar imagens ao post
- [x] Preview na box de publicar
- [x] Criação do design de post com imagem

**Comment by TheRealsz** [comment]
#### 22/09/2023, 10h - Mudança referente as imagens de posts

Realizada uma reunião no mesmo dia, foi decidido e esclarecido entre os membros do time de desenvolvimento a mudança da seguinte ideia: **Imagens em posts nao serão obrigatorias** para **Imagens em posts serão obrigatorias**, afetando assim a funcionalidade prevista anteriormente e retirada após a reunião de:

**Criação da logica para o design de posts com e sem imagem**

**Comment by TheRealsz** [comment]
**22/09/2023, 10h - Adicionamento de subTask "Preview na box de publicar"**

Ao decorrer da atividade da primeira subTask, foi percebido que para uma melhor experiencia do usuario, na box para fazer publicação, ao adicionar uma imagem, é realizado o upload dela logo na mesma box, para o usuario visualizar antes de publicar.

**Comment by TheRealsz** [comment]
### **22/09/2023, 17h36 - Funcionalidade de adicionar imagens ao post (CONCLUIDA)**

Concluida a funcionalidade do usuario poder adicionar imagem ao post dele

**Comment by TheRealsz** [comment]
# 25/09/2023, 14h45 - Funcionalidade de preview da imagem antes de publicar (CONCLUIDA)

## Componente criado/alterado
![Image](https://github.com/comandoDev/ccon-frontend/assets/77800184/5ff25aad-7d19-4f63-83ab-8a925fae41df)

## Funcionalidade criada
Agora é possivel o autor do post antes de publicar:
- Visualizar a imagem e ter a plena certeza de que é exatamente a mesma que quer publicar.
- Remover a imagem selecionada antes de publicar, caso o usuario erre ao selecionar em seu diretorio.

## Motivo da funcionalidade
Melhor experiencia do usuario e prevenir possiveis erros que o mesmo possa cometer.

## O que foi feito?

### Mudança no componente Feed.tsx
![Image](https://github.com/comandoDev/ccon-frontend/assets/77800184/da445cf2-1758-4341-bdc0-0394e1aa4617)
![Image](https://github.com/comandoDev/ccon-frontend/assets/77800184/63d8509d-d555-470e-988a-c72d4f2ebc58)

#### Antes
- Era possivel apenas adicionar a imagem, nao visualizar/deletar ela antes de poder publicar.
- O gap de cada item dentro do componente de publicar era menor **(gap-2)**
- Tendo imagem ou não, o icone de adicionar imagem continuava visivel.

#### Depois
- Possivel a visualização e a exclusao imagem antes mesmo de publicar
- Maior gap entre os items dentro do componente de publicar **(gap-4)**
- Criação de uma condicional na qual se há algo dentro do estado **pictures**, ira aparecer na tela uma div com a imagem, nome da imagem com extensão e um icone para deletar, caso contrario, irá retornar nada.
        - O icone de deletar vem com um evento de clique, ao clicar, é chamado o **setPictures** adicionando null para o estado de **pictures** e consequentemente, retirando a div com a imagem da tela do usuario.
- Ao adicionar algo dentro do estado **pictures**, o icone para adicionar imagem é retirado da tela, sendo visivel novamente apenas quando a imagem for **deletada** ao clicar no icone de deletar, ou seja, quando o valor **null** existe em **pictures**.


## Prints

### Print da funcionalidade de preview da imagem e icone de adicionar imagem retirado

- Na pagina de Feed, ao clicar em adicionar uma imagem e selecionar uma imagem, o componente de publicar irá ter esse design
![Image](https://github.com/comandoDev/ccon-frontend/assets/77800184/faf2d72b-a40a-4b1b-9e5c-3d46829dc166)

### Print da funcionalidade de deletar a imagem antes de publicar
 
- Ao adicionar a imagem, é possivel visualizar tanto o nome da imagem + extensão, quanto um icone para deletar a imagem antes de publicar.
- Seguindo o fluxo acima de adicionar imagem e visualizar o preview, ao clicar no icone de deletar, o design voltará dessa forma:
![Image](https://github.com/comandoDev/ccon-frontend/assets/77800184/013dbc9b-b9d7-4742-98b0-6e04f8825290)
