### ISSUE TITLE
[ FRONT END ] Bug Delete Post

### ISSUE THREAD

**Issue by TheRealsz** [comandoDev/ccon-frontend#6]
- [x] Identificar onde está dando o problema
- [x] Consertar bug

**Comment by TheRealsz** [comment]
## Componente alvo
ModalOptionsPost.tsx/ Posts.tsx

## Problema descrito/resolvido
- Ao seguir os passos para deletar um **Post**, no formato de tela responsivo para mobile, quando se clicava ao deletar, o modal fechava e abria novamente. A funcionalidade de deletar era realizada, porém, havia este bug do qual afetava a experiencia do usuario.

## Componentes alterados
![image](https://github.com/comandoDev/ccon-frontend/assets/77800184/36a0a23b-2605-47e5-8d9f-b43651e11fdd)

## Motivo do Bug
Slice do ModalPost mal estruturado

## O que foi feito?
### Mudança no slice.ts do ModalPost

![image](https://github.com/comandoDev/ccon-frontend/assets/77800184/26232a7e-9745-4fc3-9ab4-0caf3098429f)
![image](https://github.com/comandoDev/ccon-frontend/assets/77800184/d0cf79f6-5fd0-421f-afc4-3a42bd60baa1)

#### Antes

- Comportava apenas um reducer, sendo ela responsavel por controlar o abrir/fechar do modal e receber o post_id.

#### Depois
- Criação de dois reducers, um para abrir (openModal) e outro para fechar (closeModal).

1. openModal: 
- Altera o estado de isOpen para true e altera o valor de post_id para o valor que vem do payload.

2. closeModal:
- Altera o estado de isOpen para false e o valor de post_id para null

### Mudança no rootReducer.ts
![image](https://github.com/comandoDev/ccon-frontend/assets/77800184/31f05f79-a14f-4c86-ac1b-d4323ea16bc5)

#### Antes
- Presença apenas do modalOptionsPost no combineReducer

#### Depois 
- Retirando o modalOptionsPost (que não existe mais) e adicionando o openModal e closeModal

### Mudança no store.ts

**Comment by comandoDev** [comment]
Ótimo trabalho!
